# conda env create --file environment.yml
# mamba env create --file environment.yml
name: {{ cookiecutter.project_slug }}
channels:
  - conda-forge
  - defaults
dependencies:
  - invoke
  - jupyter
  - jupyterlab
  - matplotlib
  - nbdime
  - numpy
  - pandas
  - pip
  - plotly
  - pyprojroot
  - python={{ cookiecutter.python_version }}
  - python-dotenv
  - ruff
  - scikit-learn
  - scipy
  - seaborn
  - joblib
  {% if cookiecutter.project_packages == "All" -%}
  - category_encoders
  - lightgbm
  - missingno
  - pyjanitor
  - rapidfuzz
  - statsmodels
  - tensorflow
  - ydata-profiling
  {% endif -%}
  {% if cookiecutter.project_scope == "production" -%}
  - pre-commit
  - pytest
  {% endif -%}
  {% if cookiecutter.use_dvc == "yes" -%}
  - dvc
  {% endif -%}
